apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - fdb-operator
# Controllers will be added in future phases:
# - cilium
# - external-secrets
# - cert-manager
# - tailscale-operator
# - prometheus-operator
# - loki
# - tempo
# - trivy-operator
# - flagger
# - fdb-exporter
