apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces
# Application components will be added in future phases:
# - foundationdb
# - engine
# - control
# - dashboard
