apiVersion: v1
kind: Service
metadata:
  name: mailpit
  namespace: inferadb
  labels:
    app.kubernetes.io/name: mailpit
    app.kubernetes.io/component: email
    app.kubernetes.io/part-of: inferadb
spec:
  type: ClusterIP
  ports:
    - name: smtp
      port: 1025
      targetPort: smtp
      protocol: TCP
    - name: http
      port: 8025
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: mailpit
    app.kubernetes.io/component: email
